name = "BayesianInference"
uuid = "b4f34e8a-1234-5678-9abc-def123456789"
authors = ["Sebastian Sosa <bi@s-sosa.com>"]
version = "0.1.0"

[deps]
PythonCall = "6099a3de-0909-46bc-b1f4-468b9a2dfc0d"
CondaPkg = "992eb4ea-22a4-4c89-a5bb-47a330058a6f"

[compat]
julia = "1.6"
